# Generated by Django 5.2.1 on 2025-06-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_nickname_message_type_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
