# Generated by Django 5.2.1 on 2025-06-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_delete_room_alter_profile_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lst_seen',
            new_name='last_seen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
